import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <Main />
      {/* </main> */}
    </>
  );
}

import { useSession, signIn, signOut } from "next-auth/react";
import SetNetworkWrapper from "@/isograph-components/SetNetworkWrapper";

function Main() {
  const { data: session } = useSession();

  if (session != null) {
    return (
      <>
        <h1>Github OAuth Demo</h1>
        <p>
          Not {session.user?.name || session.user?.email}? Then Logout and login
          again
        </p>
        <button onClick={() => signOut()}>Logout</button> <br />
        <SetNetworkWrapper session={session} />
      </>
    );
  } else {
    return (
      <>
        <h1>Github OAuth Demo</h1>

        <button onClick={() => signIn("github")}>Sign in with Github</button>
      </>
    );
  }
}
